name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us briefly what bug happened.
      placeholder: What happened..
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Please confirm
      description: "Please confirm the following:"
      options:
        - label: I have checked that I am using the latest version of the plugin released.
          required: true
        - label: I have searched for similar issues, but found none.
          required: true
  - type: textarea
    id: ideas
    attributes:
      label: Any ideas?
      description: If you have an idea on how we could go about fixing this, put them here.
      placeholder: Your ideas..
  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Please add any additional info, such as screenshots, logs or code here. For code, use ``` backticks to get it highlighted.
      placeholder: Additional info..
