name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build ⚙️
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: yarn install

      - name: set development version
        run: node .github/version-bump.mjs "dev-$(git rev-parse --short HEAD)"

      - name: build
        run: yarn build

      - name: upload dist
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dist
          path: |
            manifest.json
            main.js

  test:
    runs-on: ubuntu-latest
    name: Test 🧪
    steps:
      - uses: actions/checkout@v2

      - name: test
        run: yarn test

  check-format:
    runs-on: ubuntu-latest
    name: Check format 🔍
    steps:
      - uses: actions/checkout@v2

      - name: check format
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    name: Lint ✔
    steps:
      - uses: actions/checkout@v2

      - name: lint
        run: yarn lint
